---
# tasks file for OracleUserManagement

- name: Copy the List of User to be delete from Oracle
  template:
    src: template/delete_user_oracle.csv
    dest: /home/ec2-user/

- name: Copy the Oracle Delete User Shell Script
  template:
    src: template/delete_user_oracle.sh
    dest: /home/ec2-user/

- name: Run the shell script to delete the user in db
  shell: sh /home/ec2-user/delete_user_oracle.sh
