---
# tasks file for OracleUserManagement

- name: Copy the List of User to be Update(Change Privileges) in Oracle
  template:
    src: template/user_password_change_&user_privileges_change_oracle.csv
    dest: /home/ec2-user/

- name: Copy the Oracle User Update(Change Privileges) Shell Script
  template:
    src: template/user_privileges_change_oracle.sh
    dest: /home/ec2-user/

- name: Run the shell script to change privileges of the user in db
  shell: sh /home/ec2-user/user_privileges_change_oracle.sh
