---
# tasks file for OracleUserManagement

- name: Copy the List of User to be Update(Change Password) in Oracle
  template:
    src: template/user_password_change_&user_privileges_change_oracle.csv
    dest: /home/ec2-user/

- name: Copy the Oracle User Update(Change Password) Shell Script
  template:
    src: template/user_password_change_oracle.sh
    dest: /home/ec2-user/

- name: Run the shell script to change password of the user in db
  shell: sh /home/ec2-user/user_password_change_oracle.sh
